# Generated by Django 4.1.1 on 2022-11-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20201007_0744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
