# Generated by Django 4.1.1 on 2022-11-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_delete_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(default='Matxiategi 38, 2.B', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='gorkaurzelai2000@gmail.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='municipio',
            field=models.CharField(default='Bergara', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='provincia',
            field=models.CharField(default='Guipuzkoa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
