# Generated by Django 4.1.1 on 2022-11-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_rename_profile_peluqueria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
