# Generated by Django 4.1.1 on 2022-11-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluqueria',
            name='cita_previa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='nombre_de_la_peluqueria',
            field=models.CharField(default='Peluqueria 1', max_length=150),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='servicio_a_domicilio',
            field=models.BooleanField(default=False),
        ),
    ]
